import questions from './data/questions.json';
import { criteria } from './developmentCriteria';
const SOURCE='https://tramitesenlinea.policia.gob.ni/DocT/MaterialdeEstudio/Se%C3%B1alesdeTransito.pdf';
const GROUPS=[
 {id:'verticales',title:'1. Señales verticales',description:'Se colocan junto a la vía para advertir peligros, establecer restricciones y orientar a quienes circulan.',numbers:[4,5,6,7,8,9,10,13,14,16,17,19,20,21,22,23,25,31,34,35,36,37,38,39,40,42,43,44,45,51,54,55,60]},
 {id:'horizontales',title:'2. Señalización horizontal',description:'Líneas, flechas y marcas sobre el pavimento. Identificá el color, la continuidad y el carril al que corresponden.',numbers:[24,26,27,28,29,30,32,33,41,46,47,48,49,50,56]},
 {id:'luminosas',title:'3. Señales luminosas',description:'Semáforos y señales de emergencia que se comunican mediante luces. Revisá también las indicaciones del agente.',numbers:[15,18,52,59]},
 {id:'manuales',title:'4. Señales manuales',description:'Gestos de los agentes para regular el tránsito y señales del conductor para comunicar sus maniobras.',numbers:[1,2,3,11,12,53]},
];
const preventive=new Set([7,8,9,14,21,23,31,34,35,36,37,42,45,60]);
const informative=new Set([44,54]);
const names={1:'Agente: detener la marcha',2:'Agente: continuar',3:'Agente: detenerse al borde',4:'Límite de velocidad',5:'Prohibición de adelantar',6:'Prohibición de estacionar',7:'Identificación de señales preventivas',8:'Peatones en la vía',9:'Animales en la vía',10:'Alto y vía de doble sentido',11:'Conductor: giro a la izquierda',12:'Conductor: giro a la derecha',13:'Prohibido girar a la izquierda',14:'Curva a la derecha',15:'Semáforo',16:'Prohibido retornar',17:'Prohibido girar a la izquierda',18:'Vehículo de emergencia',19:'Zona de silencio',20:'Prohibido girar a la derecha',21:'Doble sentido de circulación',22:'Continuar de frente',23:'Zona escolar',24:'Líneas y sentidos de circulación',25:'Ceda el paso',26:'Interpretación de marcas viales',27:'Líneas: prohibición de adelantar',28:'Línea discontinua: adelantar con precaución',29:'Flechas de dirección por carril',30:'Maniobras indicadas por flechas',31:'Curva y contracurva',32:'Marcas de regulación',33:'Flecha combinada: frente y giro',34:'Curva pronunciada',35:'Advertencia de curva',36:'Rotonda próxima',37:'Reducción de carriles',38:'Velocidad máxima de 45 km/h',39:'Alto: detenerse',40:'Señal reglamentaria de alto',41:'Detención antes del paso peatonal',42:'Trabajos en la vía',43:'Identificación de restricciones',44:'Identificación de señales informativas',45:'Cruce en T',46:'Adelantamiento y marcas viales',47:'Paso peatonal',48:'Prohibición de adelantar en ambos sentidos',49:'Líneas amarillas y blancas discontinuas',50:'Línea blanca continua',51:'Clasificación de la señal de alto',52:'Clasificación del semáforo',53:'Regulación a brazos',54:'Función de las señales informativas',55:'Cómo reconocer señales verticales',56:'Cómo reconocer señales horizontales',59:'Amarillo intermitente',60:'Función de las señales preventivas'};
function explanation(q){
 if(q.number===13)return 'El símbolo tachado prohíbe el giro a la izquierda.';
 if(q.number===29)return 'Las flechas indican los movimientos asignados a cada carril. Elegí con anticipación el carril que corresponda a tu destino.';
 return criteria[q.id]?.reference || q.options[q.correctIndex].text;
}
export default function TrafficSignals(){return <section id="rg-signs" className="ts-catalog"><h2>Conocé los tipos de señalización</h2><p>Cuatro grupos para estudiar la señalización. Los ejemplos abarcan el material de señales de tránsito de la Policía Nacional; algunos muestran varias figuras para compararlas.</p><nav className="rg-index" aria-label="Tipos de señalización">{GROUPS.map(group=><a key={group.id} href={'#ts-'+group.id}>{group.title.slice(3)}</a>)}</nav>{GROUPS.map(group=><section key={group.id} id={'ts-'+group.id} className="ts-group"><header><h3>{group.title}</h3><p>{group.description}</p>{group.id==='verticales'&&<p><strong>Preventivas:</strong> advierten peligros. <strong>Reglamentarias:</strong> establecen obligaciones y restricciones. <strong>Informativas:</strong> orientan e identifican vías y lugares.</p>}</header><div className="ts-grid">{group.numbers.map(number=>{const q=questions.find(item=>item.module==='senales'&&item.number===number);return <article className="ts-card" key={q.id}>{q.image&&<img src={import.meta.env.BASE_URL+q.image} alt={q.imageAlt || names[number]} loading="lazy"/>}<div>{group.id==='verticales'&&<span className="eyebrow">{preventive.has(number)?'Preventiva':informative.has(number)?'Informativa':[55].includes(number)?'Clasificación general':'Reglamentaria'}</span>}<h4>{names[number]}</h4>{/^(Figura|Uno)/i.test(explanation(q))&&<p className="ts-prompt">{q.question}</p>}<p>{explanation(q)}</p><small>{q.source.label}</small></div></article>})}</div></section>)}<p className="ts-source"><a href={SOURCE} target="_blank" rel="noreferrer">Consultar el material oficial de señales de tránsito ↗</a></p></section>}
